---
resources:
  - ../base

patches:
  - target:
      kind: PersistentVolumeClaim
      name: pvc-reader
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: sc-vol-level-dr

  - target:
      kind: Deployment
      name: pod-busybox-reader
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: dr-workload-reader
