apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Deployment
      name: deploy-vol-1
    patch: |-
      - op: replace
        path: /metadata/name
        value: deploy-vol-1-reader
  - target:
      kind: Deployment
      name: deploy-vol-2
    patch: |-
      - op: replace
        path: /metadata/name
        value: deploy-vol-2-reader
  - target:
      kind: Deployment
      name: deploy-vol-3
    patch: |-
      - op: replace
        path: /metadata/name
        value: deploy-vol-3-reader
  - target:
      kind: Deployment
      name: deploy-vol-4
    patch: |-
      - op: replace
        path: /metadata/name
        value: deploy-vol-4-reader