apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-scale-5-writer
  labels:
    appname: scale-pvc-dr
spec:
  replicas: 1
  selector:
    matchLabels:
      app-key: scale-5
  template:
    metadata:
      labels:
        app-key: scale-5
        appname: scale-pvc-dr
        scale-test: spread
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              scale-test: spread
      containers:
        - name: logger
          image: quay.io/nirsof/busybox:stable
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              emit() {
                  echo "$(date) $1" | tee -a /data/ramen.log
                  sync
              }
              trap "emit STOP; exit" TERM
              emit START
              while true; do
                  sleep 10 & wait
                  emit UPDATE
              done
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-scale-5
