apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: argocd-scale-dr-drpc
  namespace: argocd-scale-dr
spec:
  preferredCluster: ramen-ocp1
  drPolicyRef:
    name: ramen-policy-1-2
  placementRef:
    kind: Placement
    name: argocd-scale-dr-appset
  pvcSelector:
    matchLabels:
      appname: argocd-scale-dr