apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scale-28
  labels:
    appname: scale-pvc-dr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-scale-dr-2
  resources:
    requests:
      storage: 40Gi
