apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-argo-4
  labels:
    appname: argocd-scale-dr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-argocd-scale-dr-writer
  resources:
    requests:
      storage: 50Gi
