resources:
  - generated/pvcs/sc-scale-dr-1/pvc-scale-1.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-1-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-2.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-2-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-3.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-3-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-4.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-4-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-5.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-5-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-6.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-6-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-7.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-7-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-8.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-8-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-9.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-9-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-10.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-10-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-11.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-11-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-12.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-12-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-13.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-13-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-14.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-14-writer.yaml
  - generated/pvcs/sc-scale-dr-1/pvc-scale-15.yaml
  - generated/deployments/writer/sc-scale-dr-1/deploy-scale-15-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-16.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-16-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-17.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-17-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-18.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-18-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-19.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-19-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-20.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-20-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-21.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-21-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-22.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-22-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-23.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-23-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-24.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-24-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-25.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-25-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-26.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-26-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-27.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-27-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-28.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-28-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-29.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-29-writer.yaml
  - generated/pvcs/sc-scale-dr-2/pvc-scale-30.yaml
  - generated/deployments/writer/sc-scale-dr-2/deploy-scale-30-writer.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-31.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-31-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-32.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-32-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-33.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-33-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-34.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-34-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-35.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-35-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-36.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-36-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-37.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-37-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-38.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-38-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-39.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-39-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-40.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-40-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-41.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-41-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-42.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-42-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-43.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-43-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-44.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-44-reader.yaml
  - generated/pvcs/sc-scale-dr-3/pvc-scale-45.yaml
  - generated/deployments/reader/sc-scale-dr-3/deploy-scale-45-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-46.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-46-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-47.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-47-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-48.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-48-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-49.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-49-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-50.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-50-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-51.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-51-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-52.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-52-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-53.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-53-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-54.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-54-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-55.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-55-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-56.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-56-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-57.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-57-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-58.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-58-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-59.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-59-reader.yaml
  - generated/pvcs/sc-scale-dr-4/pvc-scale-60.yaml
  - generated/deployments/reader/sc-scale-dr-4/deploy-scale-60-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-61.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-61-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-62.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-62-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-63.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-63-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-64.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-64-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-65.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-65-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-66.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-66-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-67.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-67-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-68.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-68-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-69.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-69-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-70.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-70-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-71.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-71-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-72.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-72-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-73.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-73-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-74.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-74-reader.yaml
  - generated/pvcs/sc-scale-dr-5/pvc-scale-75.yaml
  - generated/deployments/reader/sc-scale-dr-5/deploy-scale-75-reader.yaml
namespace: scale-pvc-dr
