apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-argo-6
  labels:
    appname: argocd-scale-dr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-argocd-scale-dr-reader
  resources:
    requests:
      storage: 50Gi
