---
resources:
  - ../base

patches:
  - target:
      kind: PersistentVolumeClaim
      name: pvc-vol-level-dr-1
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: sc-vol-level-dr

  - target:
      kind: Deployment
      name: pod-busybox-dr-1
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: dr-workload
