apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: StatefulSet
      name: sts-1
    patch: |-
      - op: replace
        path: /metadata/name
        value: sts-1-reader
      - op: replace
        path: /spec/serviceName
        value: sts-1-reader